version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minitodo:
    build: .
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"

volumes:
  pgdata:
